name: CI Sanity

on:
  push:
  pull_request:

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f constraints.txt ]; then
            pip install --no-cache-dir -r requirements.txt -c constraints.txt
          else
            pip install --no-cache-dir -r requirements.txt
          fi

      - name: Verify pandas-ta import
        run: |
          python - << 'PY'
          import pandas_ta as ta
          print('pandas_ta version:', getattr(ta, '__version__', 'unknown'))
          PY

      - name: Launch API server
        run: |
          uvicorn src.app:app --host 127.0.0.1 --port 8000 &
          sleep 3

      - name: Health check /healthz
        run: |
          curl -sSf http://127.0.0.1:8000/healthz | tee /dev/stderr

      - name: Verify MT5 guard returns None
        env:
          ENABLE_MT5: "0"
        run: |
          python - << 'PY'
          from src.providers.mt5_client import try_import_mt5
          assert try_import_mt5() is None, 'MT5 should not be available in CI'
          print('MT5 guard OK')
          PY